/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicativo.FrmPrincipais;

/**
 *
 * @author Vinicius
 */
public class frmSplash1 extends javax.swing.JFrame {

    /**
     * Creates new form frmSplash1
     */
    public frmSplash1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setStringPainted(true);
        jProgressBar1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jProgressBar1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 280, 40));

        jLabel1.setBackground(new java.awt.Color(255, 204, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jProgressBar1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jProgressBar1AncestorAdded
        new Thread(){
            int p = 0;
            int i=0;

            @Override
            public void run(){
                while(p<110){
                    jProgressBar1.setValue(p);
                    p++;
                    i++;

                    if (i==0) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_1.png")));
                    if (i==5) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_2.png")));
                    if (i==10) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_3.png")));
                    if (i==15) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_4.png")));
                    if (i==20) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_5.png")));
                    if (i==25) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_6.png")));
                    if (i==30) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_7.png")));
                    if (i==35) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_8.png")));
                    if (i==40) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_9.png")));
                    if (i==45) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_10.png")));
                    if (i==50) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_11.png")));
                    if (i==55) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_12.png")));
                    if (i==60) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_13.png")));
                    if (i==65) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_14.png")));
                    if (i==70) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_15.png")));
                    if (i==75) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_16.png")));
                    if (i==80) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_17.png")));
                    if (i==85) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_18.png")));
                    if (i==90) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_19.png")));
                    if (i==95) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_20.png")));
                    if (i==100) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/caminhao_21.png")));

                    try{
                        sleep(20);
                    }catch(Exception e){}
                }
                frmSplash1.this.dispose();
               new FrmMenu().setVisible(true);
            }
        }.start();
    }//GEN-LAST:event_jProgressBar1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSplash1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSplash1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSplash1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSplash1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSplash1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
